universe		= docker
docker_image		= cruelmarco/pytorch_gnn:v1
executable              = run_bcos_gcn_ba2motif.sh
output                  = runlogs/ba2motif_comp.$(ClusterId).$(ProcId).out
error                   = runlogs/ba2motif_comp.$(ClusterId).$(ProcId).err
log                     = runlogs/ba2motif_comp.$(ClusterId).log
should_transfer_files   = YES
transfer_input_files    = ba2motif_data_comp.py, run_bcos_gcn.sh
stream_output = True
request_GPUs = 1
request_CPUs = 4
request_memory = 8G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1