universe		= docker
docker_image		= cruelmarco/pytorch_gnn:v1
environment = "WANDB_API_KEY=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"

executable              = run_molhiv_agg_expt.sh
output                  = runlogs/v2_MolHIV_mean_agg.$(ClusterId).$(ProcId).out
error                   = runlogs/v2_MolHIV_mean_agg.$(ClusterId).$(ProcId).err
log                     = runlogs/v2_MolHIV_mean_agg.$(ClusterId).log
should_transfer_files   = YES
transfer_input_files    = molhiv_mean_agg_v2.py, run_molhiv_agg_expt.sh
stream_output = True
request_GPUs = 1
request_CPUs = 4
request_memory = 8G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1