universe		= docker
docker_image		= cruelmarco/pytorch_gnn:v1
executable              = run_MNIST.sh
output                  = runlogs/MNIST.$(ClusterId).$(ProcId).out
error                   = runlogs/MNIST.$(ClusterId).$(ProcId).err
log                     = runlogs/MNIST.$(ClusterId).log
should_transfer_files   = YES
stream_output = True
transfer_input_files    = MNIST.py,run_MNIST.sh,../../../bcosgnn
request_GPUs = 1
request_CPUs = 1
request_memory = 4G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1
