import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Post-hoc GNNExplainer on Vanilla GIN for MNIST\n",
            "\n",
            "This notebook trains a vanilla GIN classifier on the sparsified MNIST dataset, then fits a post-hoc GNNExplainer and evaluates Jaccard@|GT| and Node AUROC."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import sys\n",
            "import random\n",
            "import time\n",
            "from pathlib import Path\n",
            "from copy import deepcopy\n",
            "\n",
            "import numpy as np\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import torch.nn.functional as F\n",
            "from sklearn.metrics import roc_auc_score, f1_score\n",
            "from tqdm import tqdm\n",
            "\n",
            "from torch_geometric.data import Data\n",
            "from torch_geometric.loader import DataLoader\n",
            "from torch_geometric.nn import GINConv, global_add_pool\n",
            "from torch_geometric.explain import Explainer, GNNExplainer, ModelConfig\n",
            "\n",
            "SEED = 42\n",
            "random.seed(SEED)\n",
            "np.random.seed(SEED)\n",
            "torch.manual_seed(SEED)\n",
            "if torch.cuda.is_available():\n",
            "    torch.cuda.manual_seed_all(SEED)\n",
            "\n",
            "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
            "print('DEVICE =', DEVICE)\n",
            "\n",
            "def find_repo_root(start: Path) -> Path:\n",
            "    for p in [start, *start.parents]:\n",
            "        if (p / 'pyproject.toml').exists() and (p / 'bcosgnn').is_dir():\n",
            "            return p\n",
            "    raise RuntimeError('Could not locate repo root (pyproject.toml + bcosgnn/).')\n",
            "\n",
            "repo_root = find_repo_root(Path.cwd())\n",
            "if str(repo_root) not in sys.path:\n",
            "    sys.path.append(str(repo_root))\n",
            "print('Repo root added:', repo_root)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def _augment_with_normalized_pos(dataset):\n",
            "    augmented = []\n",
            "    for data in dataset:\n",
            "        d = data.clone()\n",
            "        pos = d.pos.float()\n",
            "        pos_min = pos.min(dim=0).values\n",
            "        pos_max = pos.max(dim=0).values\n",
            "        denom = (pos_max - pos_min).clamp(min=1e-8)\n",
            "        pos_norm = (pos - pos_min) / denom\n",
            "        d.x = torch.cat([d.x.float(), pos_norm], dim=-1)\n",
            "        augmented.append(d)\n",
            "    return augmented\n",
            "\n",
            "def load_and_split_data(batch_size=128, add_pos_features=True):\n",
            "    print(\"Loading preprocessed sparsified .pt splits...\")\n",
            "    candidate_roots = [\n",
            "        repo_root / \"data\" / \"MNIST\" / \"sparsified_pt_splits\",\n",
            "        repo_root / \"shaique_updates\" / \"codes\" / \"MNISTsp\" / \"data\" / \"MNIST\" / \"sparsified_pt_splits\",\n",
            "    ]\n",
            "\n",
            "    split_root = None\n",
            "    for root in candidate_roots:\n",
            "        if (root / \"train_sparsified.pt\").exists() and (root / \"val_sparsified.pt\").exists() and (root / \"test_sparsified.pt\").exists():\n",
            "            split_root = root\n",
            "            break\n",
            "    if split_root is None:\n",
            "        raise FileNotFoundError(\"Could not find saved sparsified split files.\")\n",
            "\n",
            "    train_dataset = torch.load(split_root / \"train_sparsified.pt\", map_location=\"cpu\", weights_only=False)\n",
            "    val_dataset = torch.load(split_root / \"val_sparsified.pt\", map_location=\"cpu\", weights_only=False)\n",
            "    test_dataset = torch.load(split_root / \"test_sparsified.pt\", map_location=\"cpu\", weights_only=False)\n",
            "\n",
            "    if add_pos_features:\n",
            "        train_dataset = _augment_with_normalized_pos(train_dataset)\n",
            "        val_dataset = _augment_with_normalized_pos(val_dataset)\n",
            "        test_dataset = _augment_with_normalized_pos(test_dataset)\n",
            "\n",
            "    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)\n",
            "    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)\n",
            "    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)\n",
            "\n",
            "    all_labels = torch.tensor([int(d.y.item()) for d in train_dataset + val_dataset + test_dataset])\n",
            "    num_classes = int(all_labels.unique().numel())\n",
            "    num_node_features = int(train_dataset[0].num_node_features)\n",
            "\n",
            "    dataset_info = {\n",
            "        \"num_node_features\": num_node_features,\n",
            "        \"num_classes\": num_classes,\n",
            "    }\n",
            "\n",
            "    print(f\"Using split directory: {split_root}\")\n",
            "    print(f\"Loaded splits. Train: {len(train_dataset)}, Val: {len(val_dataset)}, Test: {len(test_dataset)}\")\n",
            "    print(f\"Node features: {num_node_features} (pos features added: {add_pos_features})\")\n",
            "\n",
            "    return train_dataset, val_dataset, test_dataset, train_loader, val_loader, test_loader, dataset_info\n",
            "\n",
            "BATCH_SIZE = 128\n",
            "train_dataset, val_dataset, test_dataset, train_loader, val_loader, test_loader, dataset_info = load_and_split_data(batch_size=BATCH_SIZE)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "class VanillaGINBackbone(nn.Module):\n",
            "    def __init__(self, in_channels, hidden_channels, out_channels, num_layers=4):\n",
            "        super().__init__()\n",
            "        self.node_emb = nn.Linear(in_channels, hidden_channels)\n",
            "        self.convs = nn.ModuleList()\n",
            "        self.norms = nn.ModuleList()\n",
            "        for _ in range(num_layers):\n",
            "            mlp = nn.Sequential(\n",
            "                nn.Linear(hidden_channels, 2 * hidden_channels),\n",
            "                nn.BatchNorm1d(2 * hidden_channels),\n",
            "                nn.ReLU(),\n",
            "                nn.Linear(2 * hidden_channels, hidden_channels),\n",
            "            )\n",
            "            self.convs.append(GINConv(nn=mlp, train_eps=True))\n",
            "            self.norms.append(nn.BatchNorm1d(hidden_channels))\n",
            "        self.fc1 = nn.Linear(hidden_channels, hidden_channels // 2)\n",
            "        self.fc2 = nn.Linear(hidden_channels // 2, out_channels)\n",
            "\n",
            "    def forward(self, x, edge_index, edge_attr=None, batch=None):\n",
            "        _ = edge_attr\n",
            "        if batch is None:\n",
            "            batch = torch.zeros(x.size(0), dtype=torch.long, device=x.device)\n",
            "        x = self.node_emb(x)\n",
            "        for conv, norm in zip(self.convs, self.norms):\n",
            "            x = conv(x, edge_index)\n",
            "            x = F.relu(norm(x))\n",
            "        x = global_add_pool(x, batch)\n",
            "        x = F.relu(self.fc1(x))\n",
            "        x = F.dropout(x, p=0.3, training=self.training)\n",
            "        x = self.fc2(x)\n",
            "        return x\n",
            "\n",
            "def train_one_epoch(model, loader, optimizer, criterion):\n",
            "    model.train()\n",
            "    total_loss = 0.0\n",
            "    total_correct = 0\n",
            "    total_graphs = 0\n",
            "    for batch in loader:\n",
            "        batch = batch.to(DEVICE)\n",
            "        optimizer.zero_grad()\n",
            "        logits = model(batch.x, batch.edge_index, edge_attr=getattr(batch, \"edge_attr\", None), batch=batch.batch)\n",
            "        y = batch.y.view(-1).long()\n",
            "        loss = criterion(logits, y)\n",
            "        loss.backward()\n",
            "        optimizer.step()\n",
            "        total_loss += loss.item() * batch.num_graphs\n",
            "        total_correct += (logits.argmax(dim=-1) == y).sum().item()\n",
            "        total_graphs += batch.num_graphs\n",
            "    return total_loss / max(total_graphs, 1), total_correct / max(total_graphs, 1)\n",
            "\n",
            "@torch.no_grad()\n",
            "def eval_one_epoch(model, loader, criterion):\n",
            "    model.eval()\n",
            "    total_loss = 0.0\n",
            "    total_correct = 0\n",
            "    total_graphs = 0\n",
            "    for batch in loader:\n",
            "        batch = batch.to(DEVICE)\n",
            "        logits = model(batch.x, batch.edge_index, edge_attr=getattr(batch, \"edge_attr\", None), batch=batch.batch)\n",
            "        y = batch.y.view(-1).long()\n",
            "        loss = criterion(logits, y)\n",
            "        total_loss += loss.item() * batch.num_graphs\n",
            "        total_correct += (logits.argmax(dim=-1) == y).sum().item()\n",
            "        total_graphs += batch.num_graphs\n",
            "    return total_loss / max(total_graphs, 1), total_correct / max(total_graphs, 1)\n",
            "\n",
            "def get_gnn_explainer(model, epochs: int = 200, lr: float = 0.01):\n",
            "    return Explainer(\n",
            "        model=model,\n",
            "        algorithm=GNNExplainer(epochs=epochs, lr=lr),\n",
            "        explanation_type='model',\n",
            "        node_mask_type='object',\n",
            "        edge_mask_type=None,\n",
            "        model_config=ModelConfig(\n",
            "            mode='multiclass_classification',\n",
            "            task_level='graph',\n",
            "            return_type='raw',\n",
            "        ),\n",
            "    )"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def get_ground_truth_mask(data):\n",
            "    keys_to_check = ['node_mask', 'explanation_mask']\n",
            "    for key in keys_to_check:\n",
            "        if hasattr(data, key):\n",
            "            mask = getattr(data, key)\n",
            "            if mask is not None:\n",
            "                return mask\n",
            "    return None\n",
            "\n",
            "def evaluate_custom_jaccard(explainer, model, dataset, max_graphs=None):\n",
            "    jaccard_scores = []\n",
            "    graphs = dataset[:max_graphs] if max_graphs else dataset\n",
            "    print(f\"Evaluating Jaccard on {len(graphs)} graphs...\")\n",
            "    \n",
            "    for data in tqdm(graphs):\n",
            "        data = data.to(DEVICE)\n",
            "        \n",
            "        gt_mask = get_ground_truth_mask(data)\n",
            "        if gt_mask is None: continue\n",
            "        \n",
            "        gt_mask = gt_mask.squeeze().cpu().numpy()\n",
            "        gt_nodes = set(np.where(gt_mask == 1)[0])\n",
            "        k = len(gt_nodes)\n",
            "        if k == 0: continue\n",
            "\n",
            "        with torch.no_grad():\n",
            "            batch = torch.zeros(data.num_nodes, dtype=torch.long, device=DEVICE)\n",
            "            logits = model(data.x, data.edge_index, edge_attr=getattr(data, \"edge_attr\", None), batch=batch)\n",
            "            target = logits.argmax().item()\n",
            "            \n",
            "        explanation = explainer(\n",
            "            x=data.x, \n",
            "            edge_index=data.edge_index, \n",
            "            target=torch.tensor([target], device=DEVICE),\n",
            "            edge_attr=getattr(data, \"edge_attr\", None),\n",
            "            batch=batch\n",
            "        )\n",
            "        \n",
            "        pred_mask = explanation.node_mask.detach().cpu().numpy().flatten()\n",
            "        \n",
            "        top_k_indices = np.argsort(pred_mask)[-k:]\n",
            "        pred_nodes = set(top_k_indices)\n",
            "\n",
            "        intersection = len(gt_nodes.intersection(pred_nodes))\n",
            "        union = len(gt_nodes.union(pred_nodes))\n",
            "        jaccard_scores.append(intersection / (union + 1e-8))\n",
            "\n",
            "    if not jaccard_scores: return 0.0\n",
            "    return float(np.mean(jaccard_scores))\n",
            "\n",
            "def evaluate_custom_auroc(explainer, model, dataset, max_graphs=None):\n",
            "    auroc_scores = []\n",
            "    graphs = dataset[:max_graphs] if max_graphs else dataset\n",
            "    print(f\"Evaluating AUROC on {len(graphs)} graphs...\")\n",
            "    \n",
            "    for data in tqdm(graphs):\n",
            "        data = data.to(DEVICE)\n",
            "        \n",
            "        gt_mask = get_ground_truth_mask(data)\n",
            "        if gt_mask is None: continue\n",
            "        gt_mask = gt_mask.squeeze().cpu().numpy()\n",
            "        \n",
            "        if gt_mask.sum() == 0 or gt_mask.sum() == len(gt_mask):\n",
            "            continue\n",
            "\n",
            "        with torch.no_grad():\n",
            "            batch = torch.zeros(data.num_nodes, dtype=torch.long, device=DEVICE)\n",
            "            logits = model(data.x, data.edge_index, edge_attr=getattr(data, \"edge_attr\", None), batch=batch)\n",
            "            target = logits.argmax().item()\n",
            "\n",
            "        explanation = explainer(\n",
            "            x=data.x, \n",
            "            edge_index=data.edge_index, \n",
            "            target=torch.tensor([target], device=DEVICE),\n",
            "            edge_attr=getattr(data, \"edge_attr\", None),\n",
            "            batch=batch\n",
            "        )\n",
            "        \n",
            "        pred_mask = explanation.node_mask.detach().cpu().numpy().flatten()\n",
            "        \n",
            "        try:\n",
            "            score = roc_auc_score(gt_mask, pred_mask)\n",
            "            auroc_scores.append(score)\n",
            "        except ValueError: pass\n",
            "\n",
            "    if not auroc_scores: return 0.0\n",
            "    return float(np.mean(auroc_scores))"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def _sync_if_cuda():\n",
            "    if torch.cuda.is_available():\n",
            "        torch.cuda.synchronize()\n",
            "\n",
            "def _get_batch(data):\n",
            "    return data.batch if hasattr(data, \"batch\") else torch.zeros(data.num_nodes, dtype=torch.long, device=DEVICE)\n",
            "\n",
            "def time_gnnexplainer_per_graph(gnn_explainer, model, dataset, warmup: int = 2, max_graphs: int | None = None):\n",
            "    model.eval()\n",
            "    times_ms = []\n",
            "    graphs = dataset[:max_graphs] if max_graphs is not None else dataset\n",
            "\n",
            "    # Warmup\n",
            "    for data in graphs[:warmup]:\n",
            "        data = data.to(DEVICE)\n",
            "        batch = _get_batch(data)\n",
            "        with torch.no_grad():\n",
            "            logits = model(data.x, data.edge_index, edge_attr=getattr(data, \"edge_attr\", None), batch=batch)\n",
            "            pred_label = logits.argmax(dim=-1).item()\n",
            "        _ = gnn_explainer(x=data.x, edge_index=data.edge_index, edge_attr=getattr(data, \"edge_attr\", None), batch=batch, target=torch.tensor([pred_label], device=DEVICE))\n",
            "\n",
            "    # Timing\n",
            "    for data in graphs:\n",
            "        data = data.to(DEVICE)\n",
            "        batch = _get_batch(data)\n",
            "        with torch.no_grad():\n",
            "            logits = model(data.x, data.edge_index, edge_attr=getattr(data, \"edge_attr\", None), batch=batch)\n",
            "            pred_label = logits.argmax(dim=-1).item()\n",
            "        \n",
            "        _sync_if_cuda()\n",
            "        start = time.perf_counter()\n",
            "        _ = gnn_explainer(x=data.x, edge_index=data.edge_index, edge_attr=getattr(data, \"edge_attr\", None), batch=batch, target=torch.tensor([pred_label], device=DEVICE))\n",
            "        _sync_if_cuda()\n",
            "        end = time.perf_counter()\n",
            "        times_ms.append((end - start) * 1000)\n",
            "\n",
            "    times_ms = np.asarray(times_ms, dtype=float)\n",
            "    mean_ms = float(times_ms.mean()) if times_ms.size else float('nan')\n",
            "    std_ms = float(times_ms.std()) if times_ms.size else float('nan')\n",
            "    median_ms = float(np.median(times_ms)) if times_ms.size else float('nan')\n",
            "    p90_ms = float(np.percentile(times_ms, 90)) if times_ms.size else float('nan')\n",
            "    graphs_per_s = float(1000.0 / mean_ms) if mean_ms > 0 else float('nan')\n",
            "    total_s = float(times_ms.sum() / 1000.0) if times_ms.size else float('nan')\n",
            "\n",
            "    return {\n",
            "        \"mean_ms\": mean_ms,\n",
            "        \"std_ms\": std_ms,\n",
            "        \"median_ms\": median_ms,\n",
            "        \"p90_ms\": p90_ms,\n",
            "        \"graphs_per_s\": graphs_per_s,\n",
            "        \"total_s\": total_s,\n",
            "        \"n_graphs\": int(times_ms.size),\n",
            "    }"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "HIDDEN_DIM = 64\n",
            "LR = 1e-3\n",
            "EPOCHS = 100\n",
            "EARLY_STOP_PATIENCE = 25\n",
            "\n",
            "def run_multi_seed_gnnexplainer(seeds=(11, 22, 33, 44, 55)):\n",
            "    results = []\n",
            "    \n",
            "    for seed in seeds:\n",
            "        print(f\"\\n=== Seed {seed} ===\")\n",
            "        random.seed(seed)\n",
            "        np.random.seed(seed)\n",
            "        torch.manual_seed(seed)\n",
            "        if torch.cuda.is_available():\n",
            "            torch.cuda.manual_seed_all(seed)\n",
            "            \n",
            "        model = VanillaGINBackbone(\n",
            "            in_channels=dataset_info[\"num_node_features\"],\n",
            "            hidden_channels=HIDDEN_DIM,\n",
            "            out_channels=dataset_info[\"num_classes\"],\n",
            "            num_layers=4,\n",
            "        ).to(DEVICE)\n",
            "        \n",
            "        optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)\n",
            "        criterion = nn.CrossEntropyLoss()\n",
            "        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(\n",
            "            optimizer, mode=\"min\", factor=0.5, patience=10, min_lr=1e-6\n",
            "        )\n",
            "        \n",
            "        best_val_loss = float(\"inf\")\n",
            "        best_state = None\n",
            "        epochs_no_improve = 0\n",
            "        \n",
            "        _sync_if_cuda()\n",
            "        train_start = time.perf_counter()\n",
            "        \n",
            "        for epoch in range(1, EPOCHS + 1):\n",
            "            train_loss, train_acc = train_one_epoch(model, train_loader, optimizer, criterion)\n",
            "            val_loss, val_acc = eval_one_epoch(model, val_loader, criterion)\n",
            "            scheduler.step(val_loss)\n",
            "            \n",
            "            if val_loss < best_val_loss - 1e-6:\n",
            "                best_val_loss = val_loss\n",
            "                best_state = deepcopy(model.state_dict())\n",
            "                epochs_no_improve = 0\n",
            "            else:\n",
            "                epochs_no_improve += 1\n",
            "                \n",
            "            if epoch % 5 == 0 or epoch == 1:\n",
            "                print(f\"  Epoch {epoch:03d}/{EPOCHS}: train_acc={train_acc:.4f} val_acc={val_acc:.4f} val_loss={val_loss:.4f}\")\n",
            "                \n",
            "            if epochs_no_improve >= EARLY_STOP_PATIENCE:\n",
            "                print(f\"  Early stopping at epoch {epoch}\")\n",
            "                break\n",
            "                \n",
            "        _sync_if_cuda()\n",
            "        train_time_s = time.perf_counter() - train_start\n",
            "        \n",
            "        if best_state is not None:\n",
            "            model.load_state_dict(best_state)\n",
            "            \n",
            "        print(\"Evaluating Explainer...\")\n",
            "        explainer = get_gnn_explainer(model, epochs=200, lr=0.01)\n",
            "        \n",
            "        test_loss, test_acc = eval_one_epoch(model, test_loader, criterion)\n",
            "        \n",
            "        # GNNExplainer is slow, limit to 1000 graphs or adjust as needed\n",
            "        max_graphs_explainer = 1000\n",
            "        node_jaccard = evaluate_custom_jaccard(explainer, model, test_dataset, max_graphs=max_graphs_explainer)\n",
            "        node_auroc = evaluate_custom_auroc(explainer, model, test_dataset, max_graphs=max_graphs_explainer)\n",
            "        timing = time_gnnexplainer_per_graph(explainer, model, test_dataset, warmup=2, max_graphs=max_graphs_explainer)\n",
            "        \n",
            "        print(f\"Seed {seed} Results:\")\n",
            "        print(f\"Test Acc: {test_acc:.4f} | Node Jaccard: {node_jaccard:.4f} | Node AUROC: {node_auroc:.4f}\")\n",
            "        print(f\"Explainer Time: {timing['total_s']:.2f}s ({timing['mean_ms']:.2f} ms/graph)\")\n",
            "        \n",
            "        results.append({\n",
            "            \"seed\": seed,\n",
            "            \"test_acc\": test_acc,\n",
            "            \"node_jaccard\": node_jaccard,\n",
            "            \"node_auroc\": node_auroc,\n",
            "            \"train_time_s\": train_time_s,\n",
            "            \"explainer_total_s\": timing[\"total_s\"],\n",
            "            \"explainer_mean_ms\": timing[\"mean_ms\"]\n",
            "        })\n",
            "        \n",
            "    return results"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Smoke test\n",
            "smoke_results = run_multi_seed_gnnexplainer(seeds=[123])\n",
            "print(\"Smoke test complete.\")\n",
            "print(smoke_results)\n",
            "\n",
            "# SEEDS = [11, 22, 33, 44, 55]\n",
            "# results = run_multi_seed_gnnexplainer(seeds=SEEDS)\n",
            "# import pandas as pd\n",
            "# df = pd.DataFrame(results)\n",
            "# df\n"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open("/Users/shaique/Desktop/BioInf_IMP/NMM_group/ICML/bcos_gnn/bcosgnn/shaique_updates/codes/post_hoc_analysis/post_hoc_MNIST.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)

print("Notebook created successfully.")
