universe                = docker
docker_image            = cruelmarco/pytorch_gnn:v1
executable              = run_gnnexp_mnist_hpc.sh
output                  = runlogs/gnnexp_mnist.$(ClusterId).$(ProcId).out
error                   = runlogs/gnnexp_mnist.$(ClusterId).$(ProcId).err
log                     = runlogs/gnnexp_mnist.$(ClusterId).log
should_transfer_files   = YES
stream_output           = True
transfer_input_files    = post_hoc_MNIST.py,run_gnnexp_mnist_hpc.sh,../../../pyproject.toml,../../../bcosgnn,../../../data,../MNISTsp/data/MNIST/sparsified_pt_splits
request_GPUs            = 1
request_CPUs            = 1
request_memory          = 8G
requirements            = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted     = true
+WantScratchMounted      = true
queue 1
