universe                = docker
docker_image            = cruelmarco/pytorch_gnn:v1
executable              = run_gsat_mnist_hpc.sh
output                  = runlogs/gsat_mnist.$(ClusterId).$(ProcId).out
error                   = runlogs/gsat_mnist.$(ClusterId).$(ProcId).err
log                     = runlogs/gsat_mnist.$(ClusterId).log
should_transfer_files   = YES
stream_output           = True
transfer_input_files    = gsat_mnist_hpc.py,run_gsat_mnist_hpc.sh,../../../pyproject.toml,../../../bcosgnn,../../../data
transfer_output_files   = GSAT_MNIST_Explanations.pdf,BCos_MNIST75sp_Explanations.pdf,GSAT_BCos_MNIST_Comparison.pdf
request_GPUs            = 1
request_CPUs            = 1
request_memory          = 8G
requirements            = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted     = true
+WantScratchMounted      = true
queue 1
