universe                = docker
docker_image            = cruelmarco/pytorch_gnn:v1
executable              = run_ig_mnist_hpc.sh
output                  = runlogs/ig_mnist.$(ClusterId).$(ProcId).out
error                   = runlogs/ig_mnist.$(ClusterId).$(ProcId).err
log                     = runlogs/ig_mnist.$(ClusterId).log
should_transfer_files   = YES
stream_output           = True
transfer_input_files    = IG_MNIST.py,run_ig_mnist_hpc.sh,../../../pyproject.toml,../../../bcosgnn,../../../data,../MNISTsp/data/MNIST/sparsified_pt_splits
request_GPUs            = 1
request_CPUs            = 1
request_memory          = 8G
requirements            = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted     = true
+WantScratchMounted      = true
queue 1
